root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 167, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 145, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 224, in update_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/app.py", line 221, in update_assembly
    return {
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/app.py", line 221, in update_assembly
    return {
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/app.py", line 221, in update_assembly
    return {
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/app.py", line 221, in update_assembly
    return {
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 103, in post_part
    return {
fastapi.exceptions.HTTPException
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/app.py", line 221, in update_assembly
    return {
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 103, in post_part
    return {
fastapi.exceptions.HTTPException
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/app.py", line 221, in update_assembly
    return {
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 186, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 'AssemblyModel' object has no attribute 'subassembly_name'
Traceback (most recent call last):
  File "/app/app.py", line 210, in post_assembly
    new_assembly = AnyNode(id=assembly.subassembly_name)
AttributeError: 'AssemblyModel' object has no attribute 'subassembly_name'. Did you mean: 'subassembly_names'?
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/app/app.py", line 164, in get_assembly_by_name
    raise HTTPException(status_code=403, detail="Assembly not created")
fastapi.exceptions.HTTPException
root - ERROR - 'AssemblyModel' object has no attribute 'subassembly_name'
Traceback (most recent call last):
  File "/app/app.py", line 210, in post_assembly
    new_assembly = AnyNode(id=assembly.subassembly_name)
AttributeError: 'AssemblyModel' object has no attribute 'subassembly_name'. Did you mean: 'subassembly_names'?
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/app/app.py", line 292, in get_assembly_first_level_children
    assembly_children = gAssemblies[assembly_name].children
KeyError: 'test_assembly3'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/app/app.py", line 306, in get_assembly_children
    assembly_children = gAssemblies[assembly_name].descendants
KeyError: 'test_assembly3'
root - ERROR - 'test_assembly3'
Traceback (most recent call last):
  File "/app/app.py", line 320, in get_assembly_leaves
    assembly_children = gAssemblies[assembly_name].leaves
KeyError: 'test_assembly3'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 283, in detach_part_assembly
    if part_name in gParts and gParts[part_name].parent.id == assembly_name:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 494, in get_project
    raise HTTPException(status_code=404, detail="Project name does not exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 494, in get_project
    raise HTTPException(status_code=404, detail="Project name does not exist")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 224, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 224, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 224, in post_assembly
    raise HTTPException(
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
root - ERROR - 
Traceback (most recent call last):
  File "/Users/nishantsahni/Downloads/take_home_test_flask_docker/web/app.py", line 120, in post_part
    raise HTTPException(status_code=403, detail="Part exists")
fastapi.exceptions.HTTPException
